def q_name():
    print("1.jupiter")
    print("2.venus")
    print("3.earth")
    print("4.neptune")
print("what is the biggest planet in our solar system.1")
q_name()
print("what is the biggest planet in our solar system.2")
q_name()
print("what is the biggest planet in our solar system.3")
q_name()
print("what is the biggest planet in our solar system.4")
q_name()
print("what is the biggest planet in our solar system.5")
q_name()